DROP DATABASE IF EXISTS Occa;

CREATE DATABASE Occa;

USE Occa;

CREATE TABLE events (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  startDate DATE NOT NULL,
  startTime TIME NOT NULL,
  image VARCHAR(200),
  category VARCHAR(200),
  url VARCHAR(200) NOT NULL,
  venueId INT NOT NULL,
  FOREIGN KEY venueId REFERENCES venues(id)
);

CREATE TABLE venues (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  givenId VARCHAR(200) NOT NULL,
  name VARCHAR(200) NOT NULL,
  lat DECIMAL(9,6) NOT NULL,
  lng DECIMAL(9,6) NOT NULL,
  url VARCHAR(200) NOT NULL,
  postalCode: VARCHAR(200) NOT NULL,
  image VARCHAR(200)
);